config/routes.rb
LluviaWeb::Application.routes.draw do
  devise_for :models
  resources :users

  resources :menus

  resources :pages

  resources :members

  root 'menus#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :image, styles: { medium: '200x200>', thumb: '48x48>' }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'sinLluvia'
  # GET /users
  # GET /users.json
      before_filter :authenticate_model!, :except => [:show, :index]  

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastName, :biography, :interests, :developer, :designer, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="field">
    <%= f.label :interests %><br>
    <%= f.text_area :interests %>
  </div>
  <div class="field">
    <%= f.label :developer %><br>
    <%= f.check_box :developer %>
  </div>
  <div class="field">
    <%= f.label :designer %><br>
    <%= f.check_box :designer %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= button_to 'New User', new_user_path, :method => :get, :class=>"menu" %>

</br>

<table class="tabla">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Biography</th>
      <th>Interests</th>
      <th>Developer</th>
      <th>Designer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.image.url(:thumb) %></td>
        <td><%= user.name %></td>
        <td><%= user.lastName %></td>
        <td><%= user.biography %></td>
        <td><%= user.interests %></td>
        <td><%= user.developer %></td>
        <td><%= user.designer %></td>
        <td><%= button_to 'Show', user,:method => :get, :class=>"show" %></td>
        <td><%= button_to 'Edit', edit_user_path(user),:method => :get, :class=>"show" %></td>
        <td><%= button_to 'Destroy', user, :class=>"destroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Menu', menus_path, :method => :get, :class=>"menu" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @user.image.url(:medium) %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @user.biography %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @user.interests %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @user.developer %>
</p>

<p>
  <strong>Designer:</strong>
  <%= @user.designer %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>