config/routes.rb
LluviaWeb::Application.routes.draw do
  devise_for :models
  resources :users

  resources :menus

  resources :pages

  resources :members

  root 'menus#index'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :tutorial %><br>
    <%= f.check_box :tutorial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>
<%= button_to 'New Page', new_page_path, :class=>"menu",:method => :get %>
</br>

<table class="tabla">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Description</th>
      <th>Link</th>
      <th>Body</th>
      <th>Parent</th>
      <th>Tutorial</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.titulo %></td>
        <td><%= page.description %></td>
        <td><%= page.link %></td>
        <td>...</td>
        <td><%= page.parent_id %></td>
        <td><%= page.tutorial %></td>
        <td><%= button_to 'Show', page, :class=>"show", :method => :get %></td>
        <td><%= button_to 'Edit', edit_page_path(page), :class=>"show", :method => :get %></td>
        <td><%= button_to 'Destroy', page, :class=>"destroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Menu', menus_path, :class=>"menu", :method => :get%>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>Titulo:</strong>
  <%= @page.titulo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @page.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @page.link %>
</p>
-->
 <%= markdown @page.body %>
<!--
<p>
  <strong>Parent:</strong>
  <%= @page.parent_id %>
</p>

<p>
  <strong>Tutorial:</strong>
  <%= @page.tutorial %>
</p> -->

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>