config/routes.rb
LluviaWeb::Application.routes.draw do
  devise_for :models
  resources :users

  resources :menus

  resources :pages

  resources :members

  root 'menus#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LluviaWeb</title>
  <%= stylesheet_link_tag "pages", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://www.adamaat.es/src/lluvia.js"></script>
 
</head>
<body onload="bringLLuvia(200);">
	<div id="login"
>
  <% if model_signed_in? %>
  <%= current_model.email %>
  <%= link_to "Sign_out", destroy_model_session_path, :method => :delete %>
  <% else %>
  <%= link_to "Sign_in", new_model_session_path %>
  <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/layouts/prueba.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LluviaWeb</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 
</head>
<body >

Holaa

</body>
</html>

app/views/layouts/sinLluvia.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LluviaWeb</title>
  <%= stylesheet_link_tag "menus", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
	<div id="login">
    <% if model_signed_in? %>
      <%= current_model.email %>
      <%= button_to "Sign out", destroy_model_session_path, :id => "off", :method => :delete %>
    <% else %>
      <%= button_to "Sign in", new_model_session_path, :id => "on" %>
    <% end %>
  </div>
  <div class="titulo">
    <%= image_tag("lluviaLogo1.jpg", :height => '176', :width => '439') %>
</div>
<div id="cuerpo">
<%= yield %>
</div>
</body>
</html>