config/routes.rb
LluviaWeb::Application.routes.draw do
  devise_for :models
  resources :users

  resources :menus

  resources :pages

  resources :members

  root 'menus#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_attached_file :image, styles: { medium: '200x200>', thumb: '48x48>' }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  layout 'sinLluvia'
  # GET /members
  # GET /members.json
      before_filter :authenticate_model!, :except => [:show, :index]  

  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :lastName, :biography, :interest, :image)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_area :interest %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>
<%= button_to 'New Member', new_member_path, :method => :get, :class=>"menu" %>
</br>

<table class="tabla">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Biography</th>
      <th>Interest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= image_tag member.image.url(:thumb) %></td>
        <td><%= member.name %></td>
        <td><%= member.lastName %></td>
        <td><%= member.biography %></td>
        <td><%= member.interest %></td>
        <td><%= button_to 'Show', member, :method => :get, :class=>"show" %></td>
        <td><%= button_to 'Edit', edit_member_path(member), :method => :get, :class=>"show" %></td>
        <td><%= button_to 'Destroy', member, :class=>"destroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Menu', menus_path, :method => :get, :class=>"menu" %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @member.image.url(:medium) %>
<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @member.lastName %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @member.biography %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @member.interest %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>